### BUILD FOR DEVELOPMENT

FROM node:18-alpine As development

# App directory
WORKDIR /usr/src/app

# Copy these first to avoid npm install on every change
COPY --chown=node:node package*.json ./

# clean install
RUN npm i

# Bundle app source
COPY --chown=node:node . .

# Copy NFT properties
RUN npm run copy

# Install AWS
RUN apk add --no-cache \
        python3 \
        py3-pip \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir \
        awscli \
    && rm -rf /var/cache/apk/*
RUN aws --version

# Use the node user from the image (instead of the root user)
USER node
