version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo1:27017
      - MONGODB_NAME=development-marketplace-be
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - ACTIVE_SERVICES=NFT_SERVICE,AVN_SERVICE,LISTING_SERVICE
      - PORT=5001
    command: npm run dev
    ports:
      - 5001:5001
    depends_on:
      - redis
      - mongo1
    links:
      - redis
      - mongo1

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    ports:
      - 27017:27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]

  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - ~/mongors/data2:/data/db
    ports:
      - 27018:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]

  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - ~/mongors/data3:/data/db
    ports:
      - 27019:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]

volumes:
  redis:
    driver: local
