### BUILD FOR DEVELOPMENT

FROM node:18-alpine As development

# App directory
WORKDIR /usr/src/app

# Copy these first to avoid npm install on every change
COPY --chown=node:node package*.json ./

# clean install
RUN npm i

# Bundle app source
COPY --chown=node:node . .

RUN npm run copy

# Use the node user from the image (instead of the root user)
USER node
