services:
  app:
    container_name: marketPlace
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "5002:5002"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    restart: always
    links:
      - mongo1
      - mongo2
      - mongo3
      - redis
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - redis
    
  mongo1:
    container_name: mongo1
    image: 'mongo:6'
    command: bash -c "mongod --replSet marketPlaceReplicaSet --bind_ip_all"
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 27017:27017

  mongo2:
    container_name: mongo2
    image: 'mongo:6'
    command: bash -c "mongod --replSet marketPlaceReplicaSet --bind_ip_all"
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 27018:27017

  mongo3:
    container_name: mongo3
    image: 'mongo:6'
    command: bash -c "mongod --replSet marketPlaceReplicaSet --bind_ip_all"
    volumes:
      - ./data/mongo-3:/data/db
    ports:
      - 27019:27017

  redis:
    image: 'redis:latest'
    container_name: redis
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
