{{ if and .Values.serviceAccount.create (not (eq .Values.serviceAccount.name "")) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "services.serviceAccountName" . }}
  labels:
    {{- include "services.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
